# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24d778b38de9560390d35e522fff3218601bcda9dcb7727f3bacdad1037e444b19cea51a9ec513185f7b4f950cb77da1a3463517067c02f2d2cea8116a6b2257

test:
  secret_key_base: d8660bd5c70c765100deaece827ac568538a11fa2483fc7971f1995d0b1e64ce9c6e53ff224b5d8594222cea687fccfb2b552869406584c9ce6b40e636903957

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
